sudo: required
dist: trusty
language: c++
compiler:
  - arm-none-eabi-gcc
  - arm-none-eabi-g++
cache:
  directories:
    - "${HOME}/persist"

before_script:
# Extra gcc versions
  # For teensy build
  - sudo apt-get install binutils-arm-none-eabi
  - wget https://cmake.org/files/v3.19/cmake-3.19.2.tar.gz
  - mkdir $HOME/cmake;
  - tar -xf cmake-3.19.2.tar.gz -C $HOME/cmake;
  - export PATH=$HOME/cmake/bin:$PATH;
script:
  - cd ..
  - mkdir build
  - cd build
  - cmake /home/travis/build/hristoandreev/stm32f469i-disc-esp32
  - make -j10
after_failure:
