sudo: required
dist: trusty
language: c++
compiler:
  - arm-none-eabi-gcc
  - arm-none-eabi-g++
cache:
  directories:
    - "${HOME}/persist"

before_script:
# Extra gcc versions
  # For teensy build
  - sudo apt-get install binutils-arm-none-eabi
  - wget http://http.us.debian.org/debian/pool/main/c/cmake/cmake_3.18.4-1+b1_amd64.deb
  - sudo dpkg -i cmake_3.18.4-1+b1_amd64.deb
script:
  - cd ..
  - mkdir build
  - cd build
  - $HOME/cmake/bin/cmake /home/travis/build/hristoandreev/stm32f469i-disc-esp32
  - make -j10
after_failure:
